### ISSUE TITLE
site name in URL.

### ISSUE THREAD

**Issue by ll911** [bcgov/smk-francophone#2]
maybe site name can be "en" or "fr" instead of "francophone", so URL can be `https://francophone-qa.apps.gov.bc.ca/fr` or `https://francophone-qa.apps.gov.bc.ca/en` instead of `https://francophone-qa.apps.gov.bc.ca/francophone`

**Comment by NicoledeGreef** [comment]
this repo is not being used; each franco site has its own repo now
